version: 2.1

orbs:
  android: circleci/android@2.5.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.11
    resource_class: medium

jobs:
  build-library:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache
      - run:
          name: Clean and Assemble Library
          command: ./gradlew clean assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}

  deploy-to-sonatype:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Define ORG_GRADLE_PROJECT_LIBRARY_VERSION Environment Variable at Runtime
          command: |
            if [ $CIRCLE_TAG ]
              then
                echo 'export ORG_GRADLE_PROJECT_LIBRARY_VERSION=$CIRCLE_TAG' >> $BASH_ENV
              else
                echo "export ORG_GRADLE_PROJECT_LIBRARY_VERSION=$(git tag | tail -1)-SNAPSHOT" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Import Maven Signing Key
          command: |
            echo "$GPG_SIGNING_KEY" | base64 --decode > /tmp/signingkey.asc
            gpg --import /tmp/signingkey.asc
      - run:
          name: Publish to Maven
          command: ./gradlew assemble publishToSonatype closeAndReleaseSonatypeStagingRepository

  run-ui-tests:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Run UI Tests
          command: |
            sdkmanager --install "system-images;android-23;google_apis;x86"
            ./gradlew assemble sample:connectedDebugAndroidTest

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  build-test-deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - run-ui-tests:
          name: build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
      - hold-for-approval:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
      - deploy-to-sonatype:
          name: Deploy to Maven Central
          requires:
            - hold-for-approval
          filters:
            tags:
              only: /^[0-9]+.*/

  nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - run-ui-tests:
          name: build-and-test
      - deploy-to-sonatype:
          name: Deploy Snapshot to Sonatype
          requires:
            - build-and-test
