version: 2.1

orbs:
  android: circleci/android@2.5.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.11 # Use the latest Android image
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64 # Default Java 11 for Gradle compatibility
      JDK_VERSION: 11
    resource_class: medium

jobs:
  build-library:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: java -version # Confirm that Java 11 is being used
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache
      - run:
          name: Clean and Assemble Library
          command: ./gradlew clean assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}

  deploy-to-sonatype:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Define ORG_GRADLE_PROJECT_LIBRARY_VERSION Environment Variable at Runtime
          command: |
            if [ $CIRCLE_TAG ]; then
              echo 'export ORG_GRADLE_PROJECT_LIBRARY_VERSION=$CIRCLE_TAG' >> $BASH_ENV
            else
              echo "export ORG_GRADLE_PROJECT_LIBRARY_VERSION=$(git tag | tail -1)-SNAPSHOT" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Import Maven Signing Key
          command: |
            echo "$GPG_SIGNING_KEY" | base64 --decode > /tmp/signingkey.asc
            gpg --import /tmp/signingkey.asc
      - run:
          name: Publish to Maven
          command: ./gradlew assemble publishToSonatype closeAndReleaseSonatypeStagingRepository

  run-ui-tests:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Set JAVA_HOME to Java 17 and Verify
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            java -version  # Verify Java 17 is active
      - run:
          name: Install Android System Image
          command: sdkmanager --install "system-images;android-33;google_apis;x86_64"
      - run:
          name: Switch Back to Java 11 for Gradle
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            java -version  # Verify Java 11 is active again
      - run:
          name: Run UI Tests
          command: ./gradlew assemble sample:connectedDebugAndroidTest

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  build-test-deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - run-ui-tests:
          name: build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
      - hold-for-approval:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
      - deploy-to-sonatype:
          name: Deploy to Maven Central
          requires:
            - hold-for-approval
          filters:
            tags:
              only: /^[0-9]+.*/

  nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - run-ui-tests:
          name: build-and-test
      - deploy-to-sonatype:
          name: Deploy Snapshot to Sonatype
          requires:
            - build-and-test
